language: python
python:
    - "3.5"
before_script:
    - pip install coverage && pip install python-coveralls
install: "pip install ."
services:
    - redis
script: coverage run --source qlib tests.py
after_success:
    - coveralls
